[package]
name = "aetherling"
version = "0.1.0"
authors = ["David Durst <davidbdurst@gmail.com>"]
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
